1

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -30,14 +30,22 @@ jobs:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
 
+    - name: Check Docker Hub login
+      run: |
+        echo ${{ secrets.DOCKERHUB_USERNAME }}
+        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
+
+    - name: List directory contents
+      run: ls -R
+
     - name: Display Dockerfile contents
-      run: cat jhipster-task-app/.devcontainer/Dockerfile
+      run: cat .devcontainer/Dockerfile || echo "Dockerfile not found"
 
     - name: Build and push Docker image
       uses: docker/build-push-action@v4
       with:
-        context: ./jhipster-task-app
-        file: ./jhipster-task-app/.devcontainer/Dockerfile
+        context: .
+        file: .devcontainer/Dockerfile
         push: true
         tags: ${{ secrets.DOCKERHUB_USERNAME }}/5dvtaskimagethelatest:latest
         build-args: |
